name: GitHub Actions Workflow - Manual Trigger

on:
  push:
    branches:
      - '**'  # Runs on all branches, or you can specify specific branches like 'main'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the job on'
        required: true
        default: 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      # Checkout the selected branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}  # Default to 'main' if no branch is provided

      # Setup Node.js environment
      - uses: docker://node:20-alpine
        name: Setup Node

      - name: Install dependencies
        working-directory: _tools/build-tool
        run: npm install

      - name: Assemble and pack
        working-directory: _tools/build-tool
        run: npx gulp

      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: PBO-Files
          path: build/pbo
